ground_range = 32
cactus_maxsize = 10
water_threshold = 0.8
water_number_th = ground_range * ground_range * 4
power_threshold = 1000
cactus_threshold = 1000
pumpkin_num = 2
pumpkin_size = (ground_range // pumpkin_num) -1
Weird_Substance_num = 256